"""Vingt cas métier déterministes pour le workflow agentique."""

import pytest

from app import graph as graph_module


def success_payload(extract: str | None = None) -> dict:
    return {
        "title": "Mocked Wikipedia",
        "extract": extract if extract is not None else "A complete and useful answer generated by the mocked Wikipedia service.",
    }


BUSINESS_CASES = [
    {"name": "geography_morocco", "input": "Where Morocco is located?", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Morocco is located in North Africa near Europe."), "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "capital_morocco", "input": "What is the capital of Morocco?", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Rabat is the capital city of Morocco."), "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "history", "input": "Tell me about Moroccan history", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Morocco has a rich history shaped by many civilizations."), "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "technology", "input": "What is cloud computing?", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Cloud computing provides computing resources through the internet."), "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "artificial_intelligence", "input": "What is artificial intelligence?", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Artificial intelligence enables machines to perform cognitive tasks."), "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "empty_question", "input": "", "mock_status": "FAILURE", "mock_error": "HTTP_ERROR_404", "payload": {}, "expected_status": "FALLBACK", "expected_conform": True},
    {"name": "spaces_only", "input": "    ", "mock_status": "FAILURE", "mock_error": "HTTP_ERROR_404", "payload": {}, "expected_status": "FALLBACK", "expected_conform": True},
    {"name": "api_503", "input": "Service unavailable", "mock_status": "FAILURE", "mock_error": "HTTP_ERROR_503", "payload": {}, "expected_status": "FALLBACK", "expected_conform": True},
    {"name": "api_404", "input": "Unknown subject", "mock_status": "FAILURE", "mock_error": "HTTP_ERROR_404", "payload": {}, "expected_status": "FALLBACK", "expected_conform": True},
    {"name": "api_timeout", "input": "Slow request", "mock_status": "FAILURE", "mock_error": "TIMEOUT", "payload": {}, "expected_status": "FALLBACK", "expected_conform": True},
    {"name": "api_exception", "input": "Unexpected request", "mock_status": "FAILURE", "mock_error": "EXCEPTION: mocked failure", "payload": {}, "expected_status": "FALLBACK", "expected_conform": True},
    {"name": "payload_without_extract", "input": "Incomplete payload", "mock_status": "SUCCESS", "mock_error": None, "payload": {"title": "Incomplete"}, "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "empty_extract", "input": "Empty summary", "mock_status": "SUCCESS", "mock_error": None, "payload": {"title": "Empty", "extract": ""}, "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "answer_contains_none", "input": "None value", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("This sufficiently long answer contains None and must be rejected."), "expected_status": "SUCCESS", "expected_conform": False},
    {"name": "answer_contains_nan", "input": "NaN value", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("This sufficiently long answer contains NaN and must be rejected."), "expected_status": "SUCCESS", "expected_conform": False},
    {"name": "long_question", "input": "Explain the geographical, cultural, economic and historical characteristics of Morocco in a concise but informative way.", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Morocco combines Atlantic and Mediterranean geography with a diverse cultural heritage."), "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "special_characters", "input": "Maroc : café, désert & montagnes ?", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Morocco offers mountains, desert landscapes, and vibrant historic cities."), "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "outside_domain", "input": "How do black holes form?", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Black holes can form when very massive stars collapse gravitationally."), "expected_status": "SUCCESS", "expected_conform": True},
    {"name": "simulated_slow_api", "input": "Request affected by latency", "mock_status": "FAILURE", "mock_error": "TIMEOUT", "payload": {}, "expected_status": "FALLBACK", "expected_conform": True},
    {"name": "stable_standard_repeat", "input": "Where Morocco is located?", "mock_status": "SUCCESS", "mock_error": None, "payload": success_payload("Morocco is a North African country with Atlantic and Mediterranean coastlines."), "expected_status": "SUCCESS", "expected_conform": True},
]


@pytest.mark.parametrize("case", BUSINESS_CASES, ids=[case["name"] for case in BUSINESS_CASES])
def test_twenty_business_cases(case, monkeypatch):
    def fake_api(query: str) -> dict:
        return {
            "status": case["mock_status"],
            "payload": case["payload"],
            "error": case["mock_error"],
        }

    monkeypatch.setattr(graph_module, "call_wikipedia_api", fake_api)
    monkeypatch.setattr(graph_module, "write_to_dlq", lambda **kwargs: f"dlq-{case['name']}")

    result = graph_module.run_agent(case["input"])

    assert result["status"] == case["expected_status"]
    assert result["is_conform"] is case["expected_conform"]
